import mysql from 'mysql2/promise';

const conn = await mysql.createConnection(process.env.DATABASE_URL);

const gigs = [
  // Miami venues
  { externalId: 'manual-001', source: 'manual', title: 'DJ Needed for Rooftop Pool Party', description: 'Looking for an experienced DJ for a rooftop pool party at a luxury condo in Brickell. Must have own equipment. Deep house / tech house preferred.', eventType: 'Pool Party', budget: 80000, location: 'Brickell, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-03-22 20:00:00', contactName: 'Carlos Mendez', contactEmail: 'carlos.mendez@gmail.com', contactPhone: '305-555-0101' },
  { externalId: 'manual-002', source: 'manual', title: 'Live Band for Corporate Gala', description: 'Upscale corporate event at the JW Marriott Marquis Miami. Need a 4-5 piece band that can play jazz, funk, and top 40. Black tie event.', eventType: 'Corporate Event', budget: 350000, location: 'Downtown Miami, FL', latitude: 25.7749, longitude: -80.1977, eventDate: '2026-04-05 19:00:00', contactName: 'Jennifer Walsh', contactEmail: 'jwalsh@eventpro.com', contactPhone: '305-555-0202' },
  { externalId: 'manual-003', source: 'manual', title: 'Electronic Act for Art Basel After-Party', description: 'Seeking a cutting-edge electronic act for an exclusive Art Basel after-party at a private Wynwood warehouse. 200 person capacity. Techno/industrial preferred.', eventType: 'After Party', budget: 200000, location: 'Wynwood, Miami, FL', latitude: 25.7990, longitude: -80.1993, eventDate: '2026-04-12 23:00:00', contactName: 'Sofia Reyes', contactEmail: 'sofia@wynwoodarts.com', contactPhone: '786-555-0303' },
  { externalId: 'manual-004', source: 'manual', title: 'Wedding DJ - Luxury Beachfront Ceremony', description: 'Beachfront wedding at the Fontainebleau Miami Beach. Need DJ for cocktail hour and reception. Must have wireless setup for outdoor ceremony.', eventType: 'Wedding', budget: 150000, location: 'Miami Beach, FL', latitude: 25.8103, longitude: -80.1203, eventDate: '2026-05-10 17:00:00', contactName: 'Amanda Torres', contactEmail: 'amanda.torres@outlook.com', contactPhone: '305-555-0404' },
  { externalId: 'manual-005', source: 'manual', title: 'DJ for Latin Night at Nightclub', description: 'Weekly Latin night at a popular Brickell nightclub. Looking for a DJ who can mix reggaeton, salsa, bachata, and Latin trap. Recurring gig potential.', eventType: 'Nightclub', budget: 60000, location: 'Brickell, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-03-15 22:00:00', contactName: 'Miguel Suarez', contactEmail: 'msuarez@clubmiami.com', contactPhone: '305-555-0505' },
  { externalId: 'manual-006', source: 'manual', title: 'Acoustic Duo for Restaurant Opening', description: 'New upscale seafood restaurant in Coconut Grove needs an acoustic duo for their grand opening weekend. Bossa nova, jazz, and light pop.', eventType: 'Restaurant Event', budget: 50000, location: 'Coconut Grove, Miami, FL', latitude: 25.7280, longitude: -80.2386, eventDate: '2026-03-28 18:00:00', contactName: 'Patricia Leal', contactEmail: 'pleal@groveseafood.com', contactPhone: '305-555-0606' },
  { externalId: 'manual-007', source: 'manual', title: 'House DJ for Private Villa Party', description: 'Private birthday party at a waterfront villa in Key Biscayne. 50 guests, outdoor setup. Deep house, afro house, melodic techno.', eventType: 'Private Party', budget: 120000, location: 'Key Biscayne, FL', latitude: 25.6897, longitude: -80.1625, eventDate: '2026-04-19 21:00:00', contactName: 'Roberto Fernandez', contactEmail: 'rfernandez@gmail.com', contactPhone: '786-555-0707' },
  { externalId: 'manual-008', source: 'manual', title: 'Live Electronic Act for Music Festival', description: 'Local Miami music festival seeking live electronic acts. 30-45 minute sets. Must have live instrument integration (synths, drums, etc.).', eventType: 'Music Festival', budget: 100000, location: 'Bayfront Park, Miami, FL', latitude: 25.7742, longitude: -80.1847, eventDate: '2026-05-25 16:00:00', contactName: 'David Kim', contactEmail: 'dkim@miamifest.com', contactPhone: '305-555-0808' },
  { externalId: 'manual-009', source: 'manual', title: 'DJ for Quinceañera Celebration', description: 'Quinceañera celebration at a banquet hall in Hialeah. Need DJ who can mix Latin music with current pop hits. 150 guests, 5-hour event.', eventType: 'Quinceañera', budget: 90000, location: 'Hialeah, FL', latitude: 25.8576, longitude: -80.2781, eventDate: '2026-04-26 17:00:00', contactName: 'Maria Gonzalez', contactEmail: 'mgonzalez@yahoo.com', contactPhone: '305-555-0909' },
  { externalId: 'manual-010', source: 'manual', title: 'Jazz Trio for Hotel Lobby Bar', description: 'Upscale hotel in South Beach seeking a jazz trio for Friday and Saturday evenings. 3-hour sets, 8pm-11pm. Ongoing engagement possible.', eventType: 'Hotel Residency', budget: 75000, location: 'South Beach, Miami Beach, FL', latitude: 25.7825, longitude: -80.1300, eventDate: '2026-03-21 20:00:00', contactName: 'Thomas Whitfield', contactEmail: 'twhitfield@hotelmia.com', contactPhone: '305-555-1010' },

  // Fort Lauderdale venues
  { externalId: 'manual-011', source: 'manual', title: 'DJ for Yacht Charter Party', description: 'Private yacht charter out of Fort Lauderdale marina. 40 guests, 4-hour cruise. Need DJ with compact setup. EDM, house, and party hits.', eventType: 'Yacht Party', budget: 130000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-04-04 14:00:00', contactName: 'Brian Hartley', contactEmail: 'bhartley@yachtclub.com', contactPhone: '954-555-1111' },
  { externalId: 'manual-012', source: 'manual', title: 'Band for Brewery Grand Opening', description: 'New craft brewery in Fort Lauderdale opening weekend. Need a high-energy band for Saturday afternoon. Rock, blues, and funk. Outdoor stage.', eventType: 'Grand Opening', budget: 80000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-03-29 14:00:00', contactName: 'Chris Brewer', contactEmail: 'cbrewer@ftlbrewery.com', contactPhone: '954-555-1212' },
  { externalId: 'manual-013', source: 'manual', title: 'Electronic DJ for Nightclub Residency', description: 'Las Olas nightclub seeking a resident DJ for Saturday nights. Progressive house, tech house. Must draw a crowd. Revenue sharing available.', eventType: 'Nightclub Residency', budget: 100000, location: 'Las Olas, Fort Lauderdale, FL', latitude: 26.1186, longitude: -80.1384, eventDate: '2026-03-22 22:00:00', contactName: 'Vanessa Cruz', contactEmail: 'vcruz@lasolasnights.com', contactPhone: '954-555-1313' },
  { externalId: 'manual-014', source: 'manual', title: 'DJ for Corporate Holiday Party', description: 'Tech company holiday party at the Marriott Harbor Beach. 300 employees. Need DJ for 4-hour reception. Mix of current hits and classics.', eventType: 'Corporate Party', budget: 200000, location: 'Fort Lauderdale Beach, FL', latitude: 26.1003, longitude: -80.0925, eventDate: '2026-04-18 18:00:00', contactName: 'Laura Chen', contactEmail: 'lchen@techcorp.com', contactPhone: '954-555-1414' },
  { externalId: 'manual-015', source: 'manual', title: 'Acoustic Singer for Waterfront Restaurant', description: 'Upscale waterfront restaurant on the Intracoastal seeking an acoustic singer/guitarist for Sunday brunch. 11am-2pm. Ongoing weekly gig.', eventType: 'Restaurant Residency', budget: 35000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-03-23 11:00:00', contactName: 'James Moretti', contactEmail: 'jmoretti@waterfront.com', contactPhone: '954-555-1515' },
  { externalId: 'manual-016', source: 'manual', title: 'Live Band for Wedding Reception', description: 'Wedding reception at the Pelican Grand Beach Resort. 200 guests. Need a versatile 5-piece band for 4-hour reception. Dinner music through dancing.', eventType: 'Wedding', budget: 400000, location: 'Fort Lauderdale Beach, FL', latitude: 26.1003, longitude: -80.0925, eventDate: '2026-05-16 17:00:00', contactName: 'Nicole Pemberton', contactEmail: 'npemberton@gmail.com', contactPhone: '954-555-1616' },
  { externalId: 'manual-017', source: 'manual', title: 'DJ for Pool Party at Luxury Apartment', description: 'Luxury apartment complex hosting a resident pool party. 100 guests. Need DJ from 2pm-7pm. Tropical house, nu-disco, and summer hits.', eventType: 'Pool Party', budget: 70000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-04-11 14:00:00', contactName: 'Sandra Lopez', contactEmail: 'slopez@luxuryapts.com', contactPhone: '954-555-1717' },
  { externalId: 'manual-018', source: 'manual', title: 'Electronic Act for Art Show Opening', description: 'Contemporary art gallery in Fort Lauderdale seeking an ambient/electronic act for their opening night. 80 guests. Experimental and atmospheric.', eventType: 'Art Opening', budget: 60000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-04-25 19:00:00', contactName: 'Alexis Fontaine', contactEmail: 'afontaine@artftl.com', contactPhone: '954-555-1818' },
  { externalId: 'manual-019', source: 'manual', title: 'DJ for Boat Show After-Party', description: 'Fort Lauderdale International Boat Show after-party at a private marina. 150 VIP guests. Need upscale DJ. Lounge house and deep house.', eventType: 'After Party', budget: 175000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-05-02 21:00:00', contactName: 'Richard Blackwood', contactEmail: 'rblackwood@boatshow.com', contactPhone: '954-555-1919' },
  { externalId: 'manual-020', source: 'manual', title: 'Cover Band for Sports Bar', description: 'Popular sports bar in Fort Lauderdale seeking a cover band for Friday nights. Rock, pop, and party anthems. 3-hour sets. Recurring gig.', eventType: 'Bar Gig', budget: 55000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-03-20 21:00:00', contactName: 'Tony Rizzo', contactEmail: 'trizzo@sportsbar.com', contactPhone: '954-555-2020' },

  // More Miami gigs
  { externalId: 'manual-021', source: 'gigsalad', title: 'DJ for Bachelorette Party', description: 'Bachelorette party at a luxury penthouse in Edgewater. 30 women, 5 hours. Pop hits, R&B, and party anthems. Bring own equipment.', eventType: 'Bachelorette Party', budget: 85000, location: 'Edgewater, Miami, FL', latitude: 25.7930, longitude: -80.1870, eventDate: '2026-04-03 21:00:00', contactName: 'Stephanie Moore', contactEmail: 'smoore@gmail.com', contactPhone: '786-555-2121' },
  { externalId: 'manual-022', source: 'gigsalad', title: 'Live Jazz for Charity Gala', description: 'Annual charity gala at the Pérez Art Museum Miami. 500 guests. Need a jazz quartet for cocktail hour and dinner. Black tie event.', eventType: 'Charity Gala', budget: 500000, location: 'Museum Park, Miami, FL', latitude: 25.7749, longitude: -80.1867, eventDate: '2026-05-08 18:30:00', contactName: 'Elizabeth Harrington', contactEmail: 'eharrington@pamm.org', contactPhone: '305-555-2222' },
  { externalId: 'manual-023', source: 'thebash', title: 'DJ for Sweet 16 Birthday Party', description: 'Sweet 16 birthday party at a banquet hall in Doral. 120 guests. Need DJ who can mix current pop, hip-hop, and Latin hits. Photo booth included.', eventType: 'Birthday Party', budget: 95000, location: 'Doral, FL', latitude: 25.8195, longitude: -80.3553, eventDate: '2026-04-17 17:00:00', contactName: 'Rosa Alvarez', contactEmail: 'ralvarez@gmail.com', contactPhone: '786-555-2323' },
  { externalId: 'manual-024', source: 'thebash', title: 'Electronic Producer for Fashion Show', description: 'Miami Swim Week fashion show needs a live electronic producer/DJ to create a custom soundtrack. 45-minute set. High-fashion, avant-garde sound.', eventType: 'Fashion Show', budget: 250000, location: 'Miami Beach Convention Center, FL', latitude: 25.7943, longitude: -80.1300, eventDate: '2026-05-30 19:00:00', contactName: 'Isabelle Fontaine', contactEmail: 'ifontaine@swimweek.com', contactPhone: '305-555-2424' },
  { externalId: 'manual-025', source: 'eventbrite', title: 'DJ for Rooftop Sunset Sessions', description: 'Weekly rooftop sunset sessions at a Wynwood bar. Need a DJ for Sundays 4pm-8pm. Afro house, tropical, and sunset vibes. Ongoing gig.', eventType: 'Bar Residency', budget: 45000, location: 'Wynwood, Miami, FL', latitude: 25.7990, longitude: -80.1993, eventDate: '2026-03-16 16:00:00', contactName: 'Alex Rivera', contactEmail: 'arivera@wynwoodbar.com', contactPhone: '786-555-2525' },
  { externalId: 'manual-026', source: 'eventbrite', title: 'Live Band for Product Launch Party', description: 'Tech startup product launch party at a Brickell event space. 200 guests. Need a high-energy band to set the mood. Funk, soul, and pop.', eventType: 'Product Launch', budget: 180000, location: 'Brickell, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-04-09 19:00:00', contactName: 'Mark Johnson', contactEmail: 'mjohnson@techstartup.com', contactPhone: '305-555-2626' },
  { externalId: 'manual-027', source: 'manual', title: 'DJ for Boat Party on Biscayne Bay', description: 'Private boat party on Biscayne Bay. 60 guests, 5-hour cruise. Need a DJ with compact setup. House, disco, and funk.', eventType: 'Boat Party', budget: 110000, location: 'Biscayne Bay, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-04-26 14:00:00', contactName: 'Daniel Morales', contactEmail: 'dmorales@gmail.com', contactPhone: '786-555-2727' },
  { externalId: 'manual-028', source: 'manual', title: 'Flamenco Guitarist for Spanish Restaurant', description: 'Authentic Spanish restaurant in Coral Gables seeking a flamenco guitarist for Friday and Saturday dinner service. 7pm-10pm. Ongoing.', eventType: 'Restaurant Residency', budget: 40000, location: 'Coral Gables, FL', latitude: 25.7215, longitude: -80.2684, eventDate: '2026-03-21 19:00:00', contactName: 'Carmen Vidal', contactEmail: 'cvidal@elflamenco.com', contactPhone: '305-555-2828' },
  { externalId: 'manual-029', source: 'gigsalad', title: 'DJ for Graduation Party', description: 'University of Miami graduation party at a private estate in Pinecrest. 80 guests. Hip-hop, R&B, and top 40. 4-hour event.', eventType: 'Graduation Party', budget: 75000, location: 'Pinecrest, FL', latitude: 25.6646, longitude: -80.3070, eventDate: '2026-05-09 18:00:00', contactName: 'Kevin Thompson', contactEmail: 'kthompson@gmail.com', contactPhone: '305-555-2929' },
  { externalId: 'manual-030', source: 'gigsalad', title: 'Electronic Act for Warehouse Rave', description: 'Underground warehouse event in Little Haiti. 300 capacity. Techno, industrial, and experimental electronic. 10pm-6am. Must have own setup.', eventType: 'Warehouse Event', budget: 150000, location: 'Little Haiti, Miami, FL', latitude: 25.8300, longitude: -80.1960, eventDate: '2026-04-05 22:00:00', contactName: 'Jake Winters', contactEmail: 'jwinters@undergroundmia.com', contactPhone: '786-555-3030' },

  // Broward County
  { externalId: 'manual-031', source: 'thebash', title: 'DJ for Retirement Party', description: 'Retirement party at a country club in Weston. 100 guests. Need a DJ who can play classic rock, Motown, and 80s hits. 4-hour event.', eventType: 'Retirement Party', budget: 85000, location: 'Weston, FL', latitude: 26.1003, longitude: -80.3997, eventDate: '2026-04-24 17:00:00', contactName: 'Barbara Williams', contactEmail: 'bwilliams@gmail.com', contactPhone: '954-555-3131' },
  { externalId: 'manual-032', source: 'thebash', title: 'Live Band for Bar Mitzvah', description: 'Bar Mitzvah celebration at a Davie event hall. 200 guests. Need a versatile band that can play hora, current hits, and classic rock. 5-hour event.', eventType: 'Bar Mitzvah', budget: 350000, location: 'Davie, FL', latitude: 26.0626, longitude: -80.2331, eventDate: '2026-05-23 17:00:00', contactName: 'Rachel Goldstein', contactEmail: 'rgoldstein@gmail.com', contactPhone: '954-555-3232' },
  { externalId: 'manual-033', source: 'eventbrite', title: 'DJ for Pride Festival Stage', description: 'Fort Lauderdale Pride Festival seeking DJs for the main stage. 30-minute sets. High-energy dance music, house, and pop remixes. Multiple slots available.', eventType: 'Festival', budget: 80000, location: 'Wilton Manors, FL', latitude: 26.1567, longitude: -80.1553, eventDate: '2026-06-07 12:00:00', contactName: 'Chris Daniels', contactEmail: 'cdaniels@ftlpride.com', contactPhone: '954-555-3333' },
  { externalId: 'manual-034', source: 'eventbrite', title: 'Acoustic Act for Farmers Market', description: 'Weekly farmers market in Plantation seeking acoustic performers. 2-hour sets, Sunday mornings. Indie folk, acoustic pop. Recurring weekly gig.', eventType: 'Farmers Market', budget: 25000, location: 'Plantation, FL', latitude: 26.1256, longitude: -80.2331, eventDate: '2026-03-23 10:00:00', contactName: 'Sarah Green', contactEmail: 'sgreen@plantation.gov', contactPhone: '954-555-3434' },
  { externalId: 'manual-035', source: 'manual', title: 'DJ for Pool Party at Resort', description: 'Marriott resort in Hollywood Beach hosting a summer kickoff pool party. 200 guests. Tropical house, reggaeton, and party hits. 12pm-5pm.', eventType: 'Resort Event', budget: 120000, location: 'Hollywood Beach, FL', latitude: 26.0112, longitude: -80.1220, eventDate: '2026-05-23 12:00:00', contactName: 'Mark Stevens', contactEmail: 'mstevens@marriott.com', contactPhone: '954-555-3535' },
  { externalId: 'manual-036', source: 'manual', title: 'Live Electronic Act for Gallery Opening', description: 'Contemporary art gallery in Hallandale Beach seeking a live electronic act for their opening. 100 guests. Ambient, experimental, and electronic.', eventType: 'Gallery Opening', budget: 70000, location: 'Hallandale Beach, FL', latitude: 25.9812, longitude: -80.1484, eventDate: '2026-04-16 19:00:00', contactName: 'Monica Reyes', contactEmail: 'mreyes@artgallery.com', contactPhone: '954-555-3636' },
  { externalId: 'manual-037', source: 'gigsalad', title: 'DJ for Charity Auction Gala', description: 'Annual charity auction gala at the Broward Center for the Performing Arts. 400 guests. Need a sophisticated DJ for cocktail hour and dancing.', eventType: 'Charity Gala', budget: 300000, location: 'Fort Lauderdale, FL', latitude: 26.1224, longitude: -80.1373, eventDate: '2026-05-14 18:00:00', contactName: 'Patricia Nguyen', contactEmail: 'pnguyen@charityftl.org', contactPhone: '954-555-3737' },
  { externalId: 'manual-038', source: 'gigsalad', title: 'Band for Restaurant Week Event', description: 'Upscale restaurant in Boca Raton participating in Restaurant Week. Need a live jazz/bossa nova trio for special dinner service. 3 nights.', eventType: 'Restaurant Event', budget: 120000, location: 'Boca Raton, FL', latitude: 26.3683, longitude: -80.1289, eventDate: '2026-04-08 18:00:00', contactName: 'Anthony Russo', contactEmail: 'russo@bocarestaurant.com', contactPhone: '561-555-3838' },
  { externalId: 'manual-039', source: 'thebash', title: 'DJ for Quinceanera Dance Party', description: 'Quinceanera in Miramar. 180 guests. Need DJ who specializes in Latin music - reggaeton, salsa, merengue, and bachata. 5-hour event with dinner.', eventType: 'Quinceañera', budget: 110000, location: 'Miramar, FL', latitude: 25.9867, longitude: -80.2331, eventDate: '2026-04-25 16:00:00', contactName: 'Lucia Perez', contactEmail: 'lperez@gmail.com', contactPhone: '954-555-3939' },
  { externalId: 'manual-040', source: 'thebash', title: 'Live Band for Anniversary Party', description: '25th anniversary party at a private estate in Coral Springs. 150 guests. Need a band that can play 90s hits, classic rock, and current pop.', eventType: 'Anniversary Party', budget: 200000, location: 'Coral Springs, FL', latitude: 26.2709, longitude: -80.2706, eventDate: '2026-05-30 18:00:00', contactName: 'David and Susan Miller', contactEmail: 'dmiller@gmail.com', contactPhone: '954-555-4040' },

  // More premium gigs
  { externalId: 'manual-041', source: 'manual', title: 'DJ for Ultra Music Festival Pre-Party', description: 'Official pre-party for Ultra Music Festival at a Brickell rooftop venue. 300 capacity. Techno, progressive house. Must have festival-level energy.', eventType: 'Pre-Party', budget: 250000, location: 'Brickell, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-03-27 22:00:00', contactName: 'Alex Moreno', contactEmail: 'amoreno@ultrapre.com', contactPhone: '305-555-4141' },
  { externalId: 'manual-042', source: 'manual', title: 'Hybrid Electronic Act for Venue Opening', description: 'New venue in Wynwood opening night. Seeking a hybrid electronic act (live instruments + electronic). 45-minute headline set. 400 capacity.', eventType: 'Venue Opening', budget: 300000, location: 'Wynwood, Miami, FL', latitude: 25.7990, longitude: -80.1993, eventDate: '2026-04-02 22:00:00', contactName: 'Marco Delgado', contactEmail: 'mdelgado@wynwoodvenue.com', contactPhone: '786-555-4242' },
  { externalId: 'manual-043', source: 'facebook', title: 'DJ for Boat Show VIP Party', description: 'Miami International Boat Show VIP party at a private yacht club. 200 guests. Sophisticated lounge music, deep house. Dress code enforced.', eventType: 'VIP Event', budget: 200000, location: 'Miami Beach Marina, FL', latitude: 25.7825, longitude: -80.1300, eventDate: '2026-04-16 20:00:00', contactName: 'William Prescott', contactEmail: 'wprescott@yachtclub.com', contactPhone: '305-555-4343' },
  { externalId: 'manual-044', source: 'facebook', title: 'Live Band for Fundraiser Concert', description: 'Outdoor fundraiser concert at Bayfront Park. Need 2-3 bands for a 6-hour event. Rock, indie, and alternative. 1000+ expected attendance.', eventType: 'Fundraiser Concert', budget: 150000, location: 'Bayfront Park, Miami, FL', latitude: 25.7742, longitude: -80.1847, eventDate: '2026-05-02 14:00:00', contactName: 'Jennifer Castro', contactEmail: 'jcastro@miamifund.org', contactPhone: '305-555-4444' },
  { externalId: 'manual-045', source: 'facebook', title: 'DJ for Nightclub Grand Opening', description: 'New nightclub on South Beach grand opening weekend. Need a DJ for Friday and Saturday nights. Commercial house, EDM, and top 40 remixes.', eventType: 'Grand Opening', budget: 350000, location: 'South Beach, Miami Beach, FL', latitude: 25.7825, longitude: -80.1300, eventDate: '2026-04-10 22:00:00', contactName: 'Natasha Volkov', contactEmail: 'nvolkov@sbclub.com', contactPhone: '305-555-4545' },
  { externalId: 'manual-046', source: 'manual', title: 'Acoustic Performer for Hotel Pool Bar', description: 'Boutique hotel in South Beach seeking an acoustic performer for their pool bar. Friday and Saturday afternoons, 2pm-6pm. Chill vibes, indie pop.', eventType: 'Hotel Residency', budget: 50000, location: 'South Beach, Miami Beach, FL', latitude: 25.7825, longitude: -80.1300, eventDate: '2026-03-21 14:00:00', contactName: 'Olivia Santos', contactEmail: 'osantos@boutiquehotel.com', contactPhone: '305-555-4646' },
  { externalId: 'manual-047', source: 'manual', title: 'DJ for Real Estate Developer Party', description: 'Luxury real estate developer hosting a VIP party for new condo launch in Edgewater. 150 guests. Sophisticated deep house and lounge music.', eventType: 'VIP Event', budget: 180000, location: 'Edgewater, Miami, FL', latitude: 25.7930, longitude: -80.1870, eventDate: '2026-04-23 19:00:00', contactName: 'Gregory Hoffman', contactEmail: 'ghoffman@luxurydev.com', contactPhone: '305-555-4747' },
  { externalId: 'manual-048', source: 'gigsalad', title: 'Live Band for Casino Night Event', description: 'Corporate casino night at a Doral hotel. 250 guests. Need a live band for background entertainment during casino games. Jazz, swing, and big band.', eventType: 'Corporate Event', budget: 220000, location: 'Doral, FL', latitude: 25.8195, longitude: -80.3553, eventDate: '2026-05-07 19:00:00', contactName: 'Sandra Kim', contactEmail: 'skim@eventmgmt.com', contactPhone: '305-555-4848' },
  { externalId: 'manual-049', source: 'gigsalad', title: 'DJ for Fitness Studio Launch Party', description: 'New boutique fitness studio in Brickell launching with a party. 80 guests. High-energy EDM and motivational music. 2-hour event.', eventType: 'Launch Party', budget: 65000, location: 'Brickell, Miami, FL', latitude: 25.7617, longitude: -80.1918, eventDate: '2026-03-26 18:00:00', contactName: 'Tiffany Brooks', contactEmail: 'tbrooks@fitnessstudio.com', contactPhone: '786-555-4949' },
  { externalId: 'manual-050', source: 'eventbrite', title: 'Electronic DJ for New Year\'s Eve Party', description: 'New Year\'s Eve party at a rooftop venue in Downtown Miami. 400 guests. Need a headline DJ for midnight countdown and after-party. House and techno.', eventType: 'New Year\'s Eve', budget: 500000, location: 'Downtown Miami, FL', latitude: 25.7749, longitude: -80.1977, eventDate: '2026-12-31 21:00:00', contactName: 'Victor Espinoza', contactEmail: 'vespinoza@nyemiami.com', contactPhone: '305-555-5050' },
  { externalId: 'manual-051', source: 'manual', title: 'DJ for Fashion Week After-Party', description: 'Miami Fashion Week after-party at a Design District venue. 200 guests. Avant-garde electronic, nu-disco, and fashion-forward sounds.', eventType: 'After Party', budget: 220000, location: 'Design District, Miami, FL', latitude: 25.8100, longitude: -80.1900, eventDate: '2026-04-07 23:00:00', contactName: 'Camille Beaumont', contactEmail: 'cbeaumont@fashionweek.com', contactPhone: '786-555-5151' },
  { externalId: 'manual-052', source: 'manual', title: 'Live Electronic Act for Immersive Art Experience', description: 'Immersive art installation in a Wynwood warehouse needs a live electronic act to perform during the opening. Ambient, experimental, and atmospheric.', eventType: 'Art Installation', budget: 120000, location: 'Wynwood, Miami, FL', latitude: 25.7990, longitude: -80.1993, eventDate: '2026-04-30 20:00:00', contactName: 'Yuki Tanaka', contactEmail: 'ytanaka@immersiveart.com', contactPhone: '786-555-5252' },
  { externalId: 'manual-053', source: 'facebook', title: 'DJ for Rooftop Brunch Party', description: 'Weekly rooftop brunch party at a Midtown Miami hotel. Need a DJ for Sundays 11am-3pm. Funky house, disco, and brunch vibes. Ongoing gig.', eventType: 'Brunch Party', budget: 55000, location: 'Midtown Miami, FL', latitude: 25.8050, longitude: -80.1940, eventDate: '2026-03-22 11:00:00', contactName: 'Priya Patel', contactEmail: 'ppatel@midtownhotel.com', contactPhone: '305-555-5353' },
  { externalId: 'manual-054', source: 'facebook', title: 'Band for Outdoor Concert Series', description: 'City of Miami outdoor concert series at Bayfront Park. Seeking local bands for monthly concerts. Rock, indie, and alternative. 1-hour sets.', eventType: 'Concert Series', budget: 100000, location: 'Bayfront Park, Miami, FL', latitude: 25.7742, longitude: -80.1847, eventDate: '2026-04-18 18:00:00', contactName: 'Carlos Rodriguez', contactEmail: 'crodriguez@miami.gov', contactPhone: '305-555-5454' },
  { externalId: 'manual-055', source: 'manual', title: 'DJ for Luxury Car Dealership Event', description: 'Ferrari dealership in Coral Gables hosting a VIP client appreciation event. 80 guests. Sophisticated lounge music, Italian vibes. 3-hour event.', eventType: 'VIP Event', budget: 150000, location: 'Coral Gables, FL', latitude: 25.7215, longitude: -80.2684, eventDate: '2026-05-01 19:00:00', contactName: 'Lorenzo Ferrari', contactEmail: 'lferrari@ferrarimiami.com', contactPhone: '305-555-5555' },
];

let inserted = 0;
let skipped = 0;

for (const gig of gigs) {
  try {
    await conn.query(
      `INSERT IGNORE INTO gigLeads 
       (externalId, source, title, description, eventType, budget, location, latitude, longitude, eventDate, contactName, contactEmail, contactPhone, isApproved, isRejected)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, true, false)`,
      [gig.externalId, gig.source, gig.title, gig.description, gig.eventType, gig.budget, gig.location, gig.latitude, gig.longitude, gig.eventDate, gig.contactName, gig.contactEmail, gig.contactPhone]
    );
    inserted++;
  } catch (err) {
    console.error('Error inserting', gig.externalId, err.message);
    skipped++;
  }
}

const [count] = await conn.query('SELECT COUNT(*) as total FROM gigLeads');
console.log(`\nInserted: ${inserted}, Skipped: ${skipped}`);
console.log(`Total gigs in database: ${count[0].total}`);

await conn.end();
